// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pphqpwrkckpzdgwabzeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwaHFwd3JrY2twemRnd2FiemVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDU5OTEsImV4cCI6MjA2NjYyMTk5MX0.Q3zHZMmbQ2kq2dmtcrh4TkDS-hX1eML2RycutPxnOOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);